### ISSUE TITLE
ADXL345 needs .standby() after .read_data()

### ISSUE THREAD

**Issue by electron1979** [beli-sk/IMU_sensors#3]
I found that the ADXL345 needs the .standby() after .read_data().
This is shown in adxl345.py, but not in the Wiki, Example Code.
Cheers!

**Comment by beli-sk** [comment]
Well, it does not _need_ `.standby()`, it depends on your use pattern. You can be just doing reads in a cycle and only put the sensor into standby mode after you're done.
I could mention it in the examples on the wiki however.
Thank you for the tip.
